allow repeated loading of scripts, do not close project window. new menu, View, Playback
SeleniumHQ/selenium-ide pull request #1378
Opened 2022-04-21 02:39 UTC by coinzdude

2022-04-21 03:02 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Menu/menus/projectView.ts
> +        await session.windows.onPlaybackShow()
@coinzdude - Nice use of menus!

2022-04-21 03:16 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +    projectWindow.on('focus', () => {})
@coinzdude - Can you delete these event listeners if they're not doing anything?

2022-04-21 03:21 UTC, coinzdude commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +    projectWindow.on('focus', () => {})
remove empty event listeners

2022-04-21 03:21 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +    await this.open(playbackWindowName)
@coinzdude - I think you want this to do this instead:

```
  async onPlaybackShow() {
    const window = await this.open(playbackWindowName)
    this.handlePlaybackWindow(window)
  }
```

That second function wires up the things for recording in subframes and such.

2022-04-21 03:24 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +    await this.open(playbackWindowName)
Oh wait no I'm dumb, that's called in the sub function. My bad!

2022-04-21 03:26 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +      if (name != 'project-editor') delete this.windows[name]
Good catch!

2022-04-21 03:45 UTC, coinzdude commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +    await this.open(playbackWindowName)
Hmmm.  I'm not certain actually.  Here's a code change for it and it seems to be fine?

2022-04-21 03:47 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +      if (win.title == 'Playback Window') {
This is a total nitpick, but strong equality `===` is better for most strings I think

2022-04-21 03:48 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +      if (name != 'project-editor') delete this.windows[name]
@coinzdude - Oh! I just realized, this should probably be this:

```
if (name !== projectEditorName) delete this.windows[name]
```

2022-04-21 03:51 UTC, toddtarsi requested changes
This PR looks great overall. I have a couple total nitpicks around strong equality, and only using soft equality when doing funky stuff with null or undefined kinda shapes, but thats trivial. The overall PR looks very good. Nice work!!

2022-04-21 03:52 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +    await this.open(playbackWindowName)
Yeah, you're right. This is not a good change I requested. I wrote this before I realized the open function already called this. That way my bad. Good call! 😄

2022-04-21 04:14 UTC, coinzdude commented
Reverting the view playback menu

2022-04-21 04:16 UTC, coinzdude commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +      if (win.title == 'Playback Window') {
made stronger!

2022-04-21 04:20 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +      if (win.title == 'Playback Window') {
Nice work!

2022-04-21 04:24 UTC, coinzdude commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +      if (name != 'project-editor') delete this.windows[name]
Thanks for that. I ended up swapping to check for anything that does not begin with this string so we can name the window in the future like "Project Editor - My Script"

2022-04-21 04:26 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +      if (name != 'project-editor') delete this.windows[name]
Oh neat! Very cool

2022-04-25 20:44 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +      if (!name.startsWith(projectEditorWindowName))
@coinzdude - What is going on with this line? I'm a bit worried about keeping a stale reference to a closed window.

2022-04-25 20:46 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +      this.playbackWindows.forEach((bw) => {
@coinzdude - This part should probably be outside of the iterator going over each window.

2022-04-25 20:46 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +          win.close()
@coinzdude - I think you'll want to call win.close() even if window is already closable

2022-04-25 21:22 UTC, coinzdude commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +          win.close()
Great catch. I think I got this now?

2022-04-25 21:24 UTC, coinzdude commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +      this.playbackWindows.forEach((bw) => {
I'm not really sure how this works, or the 'right' way to close these.  I don't know how to get these outside of the iterator either. Should I put the windows to close into another list and then close those?

2022-04-25 21:40 UTC, coinzdude commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +      this.playbackWindows.forEach((bw) => {
I submitted some changes here. Let me know.

2022-04-25 21:43 UTC, toddtarsi commented on packages/selenium-ide/src/browser/windows/ProjectEditor/components/Suites/SuitesDrawer.tsx
> +          if (b.name < a.name) {
@coinzdude - Okay, one more critique here. I'd recommend changing this to use localeCompare:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

```
.sort((a, b) => a.localeCompare(b))
```

It will reduce the complexity of this and alphabetize things in a more cross-language-y way.

2022-04-25 21:44 UTC, toddtarsi commented on packages/selenium-ide/src/browser/windows/ProjectEditor/components/Tests/TestsDrawer.tsx
> +        .sort((a, b) => {
Same as above here

2022-04-25 21:51 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +        !win.title.startsWith('Command List')
I don't think this will ever be a title we need to worry about, so this line can be dropped.

2022-04-25 21:52 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +    // await this.close(projectEditorWindowName)
You can drop this line instead of commenting it. It can go. I can see that we aren't closing the project window now.

2022-04-25 21:53 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +        !win.title.startsWith('Command List')
Honestly, you might be able to get rid of this entire block. The only windows that should be open after forcing closed splash should be the project editor window and N playback windows. By iterating those, I don't think this block should run for any windows.

2022-04-25 21:54 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +        !win.title.startsWith('Command List')
To be clear, I mean the whole `BrowserWindow.getAllWindows().forEach(...)` block

2022-04-25 21:55 UTC, toddtarsi commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +      console.debug('projectWindow on closed')
I think this logger can go, same with the logger two lines down. If you want to keep them, we might want to move them behind a namespace like we do here:

https://github.com/SeleniumHQ/selenium-ide/blob/11389d058c9850004d34c165b5c7aa2b84225645/packages/selenium-ide/src/main/api/classes/Handler.ts#7

2022-04-26 00:49 UTC, coinzdude commented on packages/selenium-ide/src/browser/windows/ProjectEditor/components/Suites/SuitesDrawer.tsx
> +          if (b.name < a.name) {
Much better!

2022-04-26 00:49 UTC, coinzdude commented on packages/selenium-ide/src/browser/windows/ProjectEditor/components/Tests/TestsDrawer.tsx
> +        .sort((a, b) => {
done!

2022-04-26 00:50 UTC, coinzdude commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +        !win.title.startsWith('Command List')
I tried ignoring 'command list' but I couldn't as it would get closed.  'command list' appears to be a temporary name on the way to getting the name 'project editor'

2022-04-26 00:53 UTC, coinzdude commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +    // await this.close(projectEditorWindowName)
done

2022-04-26 00:56 UTC, coinzdude commented on packages/selenium-ide/src/main/session/controllers/Windows/index.ts
> +        !win.title.startsWith('Command List')
On this, in my testing, if I don't exclude both of these window names, then the app will close when loading a project

2022-04-26 01:38 UTC, toddtarsi approved these changes
LGTM 👍 Nice work!

2022-04-26 04:25 UTC, toddtarsi approved these changes
Nice work. Merging!

2022-04-26 04:26 UTC, merged